# Generated by Django 4.1.7 on 2023-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_facebook_alter_customuser_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
