# Generated by Django 4.1.7 on 2023-04-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendee',
        ),
    ]
