# Generated by Django 4.1.7 on 2023-04-11 07:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
