# Generated by Django 4.1.7 on 2023-04-03 13:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(default='gfydgs', unique=True, verbose_name='news slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
