# Generated by Django 4.1.7 on 2023-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(unique=True, verbose_name='news slug'),
        ),
    ]
