# Generated by Django 4.1.7 on 2023-04-03 18:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_news_slug_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
