# Generated by Django 4.1.7 on 2023-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='telephone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
