# Generated by Django 4.1.7 on 2023-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_performance_review',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
