# Generated by Django 4.1.7 on 2023-04-19 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 7, 7, 42, 457905, tzinfo=datetime.timezone.utc)),
        ),
    ]
