# Generated by Django 4.1.7 on 2023-05-04 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 7, 58, 59, 116830, tzinfo=datetime.timezone.utc)),
        ),
    ]
