# Generated by Django 4.1.7 on 2023-05-05 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 7, 55, 52, 428667, tzinfo=datetime.timezone.utc)),
        ),
    ]
