# Generated by Django 4.1.7 on 2023-05-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 14, 6, 43, 526395, tzinfo=datetime.timezone.utc)),
        ),
    ]
