# Generated by Django 4.1.7 on 2023-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_progressreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
