# Generated by Django 4.1.7 on 2023-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_assignment_additional_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='milestones',
            field=models.ManyToManyField(blank=True, to='tasks.milestone'),
        ),
    ]
