# Generated by Django 4.1.7 on 2023-05-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_milestone_task_milestones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestones',
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tasks.task'),
        ),
    ]
